generate_music_list_task:
  description: >
    Interpret the user's prompt describing the type of playlist they want to create.
    The prompt may include genre, era, occasion, mood, and optionally the desired number of songs or total duration of the playlist (in minutes).
    Based on this input, generate a list of songs that match the theme and approximate the requested length or song count.
    User Prompt is: {user_prompt}
  expected_output: >
    A list of songs formatted as:
    - "Song Title" by Artist Name

    The list should include approximately the number of songs or total duration specified by the user.
    If the user does not specify either, generate a default playlist of 10 songs.
  agent: music_researcher

fetch_spotify_uris_task:
  description: >
    Receive a list of songs with their respective artist names and use the Spotify Web API to search for each one.
    Retrieve the Spotify URL for each track, ensuring the match is as accurate as possible based on title and artist.
    This task relies on an external Tool that queries the Spotify API directly.
    Handle edge cases where a song may not be found by skipping or logging it for review.
    Use the Spotify Web API to search for tracks. The token is already available as the `token` input. Do not generate or hardcode it.
  expected_output: >
    Use the Spotify Web API to search for tracks. The token is already available as the `token` input {token}. Do not generate or hardcode it.
    A single comma-separated string (wuthout spaces) containing only the valid Spotify url (example: uris=spotify:track:4iV5W9uYEdYUVa79Axb7Rh,spotify:track:1301WleyT98MSxVHPZCA6M,spotify:episode:512ojhOuo1ktJprKbVcKyQ).
    If a track cannot be found, omit it from the output.
  agent: spotify_uri_fetcher

create_and_populate_playlist_task:
  description: >
    Using the provided Spotify access token, user ID, list of track URIs, playlist name and description,
    create a new playlist in the user's Spotify account and add the songs to it.
    This task uses the Spotify Web API and assumes valid authentication via OAuth.
    Do not attempt to generate or refresh the token manually.
    Use the Spotify Web API to search for tracks. The token is already available as the `token` input {token}. Do not generate or hardcode it.
  expected_output: >
    A JSON object containing the playlist URL and name. For example:
    {
      "playlist_url": "https://open.spotify.com/playlist/7wDH1tHMWUcdq5yMb5vVeK",
      "name": "Minha Playlist da Crew"
    }
  agent: spotify_playlist_creator
